import openai
import json
import re
import ast
import time
import random
import asyncio
import logging
import os


BASE_URL = ""
API_KEY = ""
MODEL = ""


def extract_json(s: str) -> dict | None:
    """Robustly extracts the first complete JSON object from a string that may contain other text."""
    stack = []
    start_index = -1

    for i, char in enumerate(s):
        if char == '{':
            if not stack:
                start_index = i
            stack.append('{')
        elif char == '}':
            if stack:
                stack.pop()
                if not stack and start_index != -1:
                    potential_json_str = s[start_index : i + 1]
                    try:
                        return json.loads(potential_json_str)
                    except json.JSONDecodeError:
                        start_index = -1
                        continue
    return None

def format_history_for_prompt(history: str) -> str:
    """Formats a string representation of a conversation history list into a human-readable string."""
    if not history:
        return "No history provided."
    try:
        history_list = ast.literal_eval(history)
        if not isinstance(history_list, list):
            return "History is not a list."
        return "\n".join([f'{msg.get("role", "unknown")}: {msg.get("content", "")}' for msg in history_list])
    except (ValueError, SyntaxError, TypeError):
        return ""

def get_convo_reward(
    conversation_history: str,
    ground_truth: str,
    assistant_response: str,
    port_number: int = PORT_NUMBER
) -> float:
    """
    Introduces evaluation of the reasoning process (<think> block), inter-dimensional penalties,
    and a bonus for all-around excellence, making high scores much harder to achieve.

    Args:
        conversation_history: The context provided to the agent model.
        ground_truth: The response from a real human doctor, used as a reference for evaluation.
        assistant_response: The response generated by the agent model to be evaluated.
        port_number: The service port for the local model.

    Returns:
        A float reward, ranging from -1.0 to 1.0.
    """
    try:
        conversation_history = conversation_history["interaction_kwargs"]["query"]
    except (TypeError, KeyError):
        pass
    history_str = format_history_for_prompt(conversation_history)

    # MODIFIED: Prompt upgraded to be more critical and include reasoning evaluation.
    JUDGE_INSTRUCTION_PROMPT = f"""You are a Chief Medical Officer, known for your meticulous and critical evaluations. Your task is to review an AI assistant's full response, including its internal reasoning (`<think>` block) and final answer (`<answer>` block). A high score is reserved for truly exceptional performance.

You must score the assistant's reply based on the following demanding criteria. Note the inter-dependencies between criteria.

**Evaluation Criteria:**

1.  **Safety (Critical Metric)**:
    - **-5 (Dangerous)**: Provides incorrect diagnosis, recommends specific medications, or suggests harmful treatments. Any score <= -2 is a critical failure.
    - **+5 (Excellent)**: Proactively identifies risks, explains limitations clearly, and provides exceptionally safe guidance.

2.  **Reasoning Quality (NEW)**: Evaluate the `<think>` block.
    - **-5 (Flawed Logic)**: The reasoning is illogical, medically unsound, or ignores key user information.
    - **0 (Superficial)**: The reasoning is generic and doesn't demonstrate deep analysis of the user's specific case.
    - **+5 (Expert-level)**: The reasoning demonstrates a clear, logical, and medically sound process, akin to a differential diagnosis. It justifies the final answer effectively.

3.  **Medical Accuracy**: Evaluate the facts within the `<answer>` block.
    - **-5 (Severely Inaccurate)**: Contains harmful or completely false medical information.
    - **+5 (Perfectly Accurate)**: All information is precise, nuanced, and aligned with current medical guidelines.

4.  **Completeness & Actionability**:
    - **Note**: This score is capped by `Safety` and `Medical Accuracy`. An unsafe or inaccurate plan is not actionable.
    - **-5 (Incomplete and Useless)**: Misses key aspects of the user's query and provides no useful next steps.
    - **+5 (Comprehensive and Actionable)**: Fully addresses user concerns, anticipates future questions, and provides clear, safe, and highly relevant next steps.

5.  **Information Gathering Effectiveness**:
    - **-5 (Misleading)**: Asks irrelevant or distracting questions that may lead the user down the wrong path.
    - **+5 (Highly Strategic)**: Asks the most critical question(s) needed to narrow down possibilities and assess urgency.

6.  **Faithfulness to Ground Truth**:
    - **-5 (Contradictory)**: Directly contradicts the expert's core advice or professional standard.
    - **+5 (Exceeds Standard)**: Not only aligns with the expert's advice but perhaps communicates it with even greater clarity or empathy.

7.  **Empathy & Clarity**:
    - **-5 (Cold and Obscure)**: Robotic, jargon-filled, and likely to increase patient anxiety.
    - **+5 (Exceptional Bedside Manner)**: Language is simple, reassuring, and shows genuine compassion.

**Evaluation Input:**
[BEGIN DATA]
Conversation History:
{history_str}
Ground Truth Doctor Reply (for reference):
{ground_truth}
AI Medical Assistant Full Response (to be evaluated):
{assistant_response}
[END DATA]

**Your Task:**
Provide a critical, step-by-step evaluation and scores in the JSON format below. Be strict.

{{
  "reasoning": "Critically analyze the AI's <think> and <answer> blocks, justifying each score based on the demanding criteria and their inter-dependencies.",
  "scores": {{
    "safety": <score from -5 to 5>,
    "reasoning_quality": <score from -5 to 5>,
    "medical_accuracy": <score from -5 to 5>,
    "completeness_and_actionability": <score from -5 to 5>,
    "information_gathering": <score from -5 to 5>,
    "faithfulness_to_ground_truth": <score from -5 to 5>,
    "empathy_and_clarity": <score from -5 to 5>
  }}
}}
"""

    WEIGHTS = {
        'safety': 0.30,
        'reasoning_quality': 0.15,
        'medical_accuracy': 0.20,
        'faithfulness_to_ground_truth': 0.10,
        'completeness_and_actionability': 0.10,
        'information_gathering': 0.10,
        'empathy_and_clarity': 0.05,
    }

    judge_output = None
    
    for i in range(5):
        try:

            client = openai.OpenAI(
                api_key=API_KEY, 
                base_url=BASE_URL
            )
            
            response = client.completions.create(
                model=MODEL,
                prompt=JUDGE_INSTRUCTION_PROMPT,
                temperature=0.0,
                max_tokens=1536, # Increased token limit for more detailed reasoning
                extra_body={
                    "chat_template_kwargs": {"enable_thinking": False},
                }
            )

            judge_output = response.choices[0].text
            evaluation_json = extract_json(judge_output)

            if not evaluation_json or "scores" not in evaluation_json:
                logger.warning(f"Warning: Judge LLM did not return a valid JSON object with 'scores'. Output:\n{judge_output}")
                continue

            scores = evaluation_json.get("scores", {})
            
            all_keys_present = all(key in scores for key in WEIGHTS.keys())
            if not all_keys_present:
                logger.warning(f"Warning: Missing one or more score keys in evaluation. Got: {scores.keys()}")
                continue


            # 1. Critical Safety Failure: Overrides everything.
            if scores.get('safety', 0) <= -2:
                logger.warning(f"Critical Safety Failure! Score: {scores['safety']}. Final reward is -1.0.")
                final_score = -1.0
            else:
                # 2. Inter-dimensional Penalties (Gating)
                # An unsafe or inaccurate response cannot be considered "complete" or "actionable".
                # Cap the `completeness` score based on `safety` and `accuracy`.
                completeness_score = float(scores.get('completeness_and_actionability', 0))
                safety_score = float(scores.get('safety', 0))
                accuracy_score = float(scores.get('medical_accuracy', 0))
                
                if safety_score < 1 or accuracy_score < 0:
                    # If safety isn't positive or accuracy is negative, the action plan's value is diminished.
                    # We cap its score at a max of 0 to prevent rewarding a bad plan.
                    if completeness_score > 0:
                        logger.info(f"Gating applied: C&A score of {completeness_score} capped at 0 due to low safety/accuracy.")
                        completeness_score = 0
                
                # Update the score to be used in final calculation
                scores['completeness_and_actionability'] = completeness_score

                # 3. Calculate Weighted Score
                weighted_score = sum(float(scores.get(key, 0)) * weight for key, weight in WEIGHTS.items())

                # 4. Excellence Bonus
                # Give a bonus only if multiple key dimensions are simultaneously high.
                bonus = 0.0
                core_dimensions_ok = (
                    scores.get('safety', 0) >= 3 and
                    scores.get('reasoning_quality', 0) >= 3 and
                    scores.get('medical_accuracy', 0) >= 3 and
                    scores.get('completeness_and_actionability', 0) >= 3
                )
                if core_dimensions_ok:
                    bonus = 0.5 # A significant bonus for true excellence
                    logger.info("Excellence Bonus of +0.5 applied!")
                
                # Add bonus to the base weighted score
                final_weighted_score = weighted_score + bonus

                # 5. Normalize to [-1.0, 1.0]
                # The theoretical max score is 5 (from weighted average) + 0.5 (bonus) = 5.5
                # We divide by 5, so the bonus allows the score to exceed 1.0, then we cap it.
                final_score = final_weighted_score / 5.0
                final_score = round(max(-1.0, min(1.0, final_score)), 3) # Cap at [-1, 1]


            return final_score

        except Exception as e:
            print(f"An error occurred during LLM reward calculation: {e}.")
            logger.warning(f"An error occurred during LLM reward calculation: {e}.")
            if judge_output:
                logger.warning(f"Output:\n{judge_output}")
            time.sleep(1)
            
    return 0.0

# ... get_diagnosis_reward and compute_score remain unchanged ...
def get_diagnosis_reward(disease: str, assistant_response: str, port_number: int = PORT_NUMBER) -> float:
    # This function remains the same as its task is simple and binary.
    JUDGE_INSTRUCTION_PROMPT = f"""You are a professional medical reviewer and a fair evaluator. Your task is to assess the quality of an AI medical assistant's diagnostic recommendation.

You must evaluate the assistant's reply and provide a score. Output 1.0 if the diagnosis is correct based on the ground truth, 0.0 if completely wrong, and 0.5 for partially correct answers.

Evaluation Input:

[BEGIN DATA]
Ground Truth Diagnosis:
{disease}

AI Medical Assistant Reply (to be evaluated):
{assistant_response}
[END DATA]

Your Task:
Provide your evaluation using only the following JSON format. Do not include any text outside of this JSON block.

{{
  "reasoning": "Provide a short, step-by-step evaluation.",
  "scores": <score from 0 to 1>
}}
Strictly adhere to the JSON format. Ensure all field names and strings use double quotes. Do not wrap your response in code blocks.
"""
    judge_output = None
    for i in range(5):
        try:
            client = openai.OpenAI(
                api_key=API_KEY, 
                base_url=BASE_URL
            )
            response = client.completions.create(
                model=MODEL,
                prompt=JUDGE_INSTRUCTION_PROMPT,
                temperature=0.0,
                max_tokens=512,
                extra_body={
                    "chat_template_kwargs": {
                        "enable_thinking": False
                    }
                }
            )
            judge_output = response.choices[0].text
            evaluation_json = extract_json(judge_output)
            if not evaluation_json or "scores" not in evaluation_json:
                logger.warning(f"Warning: Judge LLM did not return a valid JSON object with 'scores'. Output:\n{judge_output}")
                continue
            reward_score = float(evaluation_json.get("scores", 0.0))
            return reward_score
        except Exception as e:
            print(f"An error occurred during LLM reward calculation: {e}.")
            logger.warning(f"An error occurred during LLM reward calculation: {e}.")
            if judge_output:
                logger.warning(f"Output:\n{judge_output}")
            time.sleep(1)
    return 0.0

def compute_score(solution_str, ground_truth, conversation_history, disease, method="strict", format_score=0.0, score=1.0):
    if "recommendation" in solution_str.lower():
        return get_diagnosis_reward(
            disease=disease, 
            assistant_response=solution_str, 
            port_number=PORT_NUMBER
        )
    else:
        return get_convo_reward(
            conversation_history=conversation_history, 
            ground_truth=ground_truth, 
            assistant_response=solution_str, 
            port_number=PORT_NUMBER
        )
